name: NixOS

on:
  push:
    branches: [main]

jobs:
  build-fili:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true

    - name: add deploy key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_DEPLOY_KEY }} 
        known_hosts: '${{ secrets.FILI_KNOWN_HOSTS }} '

    # - name: "Install Nix ❄️"
    #   uses: cachix/install-nix-action@v18
    # - name: "Install Cachix ❄️"
    #   uses: cachix/cachix-action@v12
    #   with:
    #     name: deployments
    #     authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - name: "Build NixOS config ❄️"
      run: |
        nix develop --command deploy